### ISSUE TITLE
TurboTap not supported

### ISSUE THREAD

**Issue by Exalm** [libretro/beetle-pce-fast-libretro#100]
TurboTap is a controller splitter for TurboGrafx-16 that allows plugging in 5 controllers. Multiplayer in Bomberman seems to require it, so it would be nice to support this.

**Comment by retro-wertz** [comment]
Hi. kindly test the SuperGrafx( if available in system you will be using) core instead and see if multitap/5-player support works there (it was tested on 5-player Moto Roaders by me and myself using the same gamepad to control the 5 race cars coz i dont have friends nor have many gamepads :D).
ill backport it of it works

**Comment by Exalm** [comment]
Hm, I've experimented a bit more with it, and seems it already works, but only if there are 2+ controllers plugged in (incl. keyboard). So, it actually already worked, sorry :o
