### ISSUE TITLE
Turbo option is broken.

### ISSUE THREAD

**Issue by bslenul** [libretro/beetle-pce-fast-libretro#135]
Hey, turbo seems to not work properly (tested on W10, on a Linux VM and on a SNESC):

* With the `Turbo ON/OFF Toggle` option set to ON, pressing X/Y pops a notification saying turbo is enabled for I and II but turbo doesn't work.
* With the `Turbo ON/OFF Toggle` option set to OFF, you still get the notifications when pressing X/Y which shouldn't happen! And turbo still doesn't work.

I bisected already, looks like the bug started with this commit: 7e92d19a80bde4827dfd0927b016f38a85e92701.

The previous commit (614b6c39a9dc32428126d134606db44a9f015408) works as intended: option ON you get the notifications and turbo is actually working when you press X/Y, option OFF X/Y doesn't do anything.

**edit:**  
And btw, it's not only the toggle option that is not working, if I set `P1 Turbo I` and `P1 Turbo II` to ON, same results, it doesn't work.

Also, just tested with the non-fast version of the core and everything seems to work fine in this one.

**Comment by negativeExponent** [comment]
turbo loop in this core it generally problematic even in the past with some games. these has been fixed in other pce/sgx cores. and the related core-option needs cleanup as well.

**Comment by KMFDManic** [comment]
Thanks for the fix @negativeExponent :)

**Comment by negativeExponent** [comment]
> Thanks for the fix @negativeExponent :)

i have not sent a fix. just pointing out the problem. some1 has to make a PR on it

on a related note, the pce suffers the same turbo button issue that this core has
