### ISSUE TITLE
[Performance Discussion] PCE Accurate is slower than Mednafen PCE

### ISSUE THREAD

**Issue by negativeExponent** [libretro/beetle-pce-fast-libretro#142]
**(THIS IS NOT A THIS CORE VS THAT CORE DISCUSSION. THE PURPOSE AT LEAST IS TO OPTIMIZE THE PORT FURTHER IF POSSIBLE)**

the libretro_pce core is ~~significantly~~ slower compared to Mednafen PCE.

tested by running the cores in fast-forward mode. im aware this is not the best way to compare as i am bottlenecking my cpu at 100% when running this way but still its slower:

Common setups:
- everything is on default settings both versions as much as possible
- both seems to prefer audio enabled when fast-forwarding so lets leave that as is.
- retroarch uses 16 bit for colors, so i assume the slowdown is not about the color-format
- using linux-arch with xfce4's window manager disabled for best framerate
- retroarch uses RGUI with blings disabled (at least the animation stuff)
- Mednafen has a max fast-forward rate of 15x, but i think i am not at its max limit yet based on screenshot below

**libretro PCE:**
![pce_libretro](https://user-images.githubusercontent.com/54053706/71538586-9f0d2d80-2968-11ea-8a06-62970127fb94.png)

**Mednafen PCE with frameskip enabled:**
![pce_mednafen](https://user-images.githubusercontent.com/54053706/71538602-e0054200-2968-11ea-893b-6f64f213a156.png)

**Mednafen PCE with frameskip disabled:**
![pce_mednafen_no_frameskip](https://user-images.githubusercontent.com/54053706/71545059-8f6e0300-29c1-11ea-8c93-183c9531c1f6.png)

I cannot do the same comparison with pce_fast or supergrafx since Mednafen is always at max fps with those (about 900fps) and i haven't found yet if mednafen's fast-forward multiplier limit can be changed or set to infinite

**Mednafen PCE_Fast with SuperGrafx enabled, frameskip enabled:**
![pce_fast_supergrafx_mednafen](https://user-images.githubusercontent.com/54053706/71542677-36dc3d00-29a4-11ea-8cd2-6b4aaf822325.png)

**Comment by hizzlekizzle** [comment]
Does mednafen's fast-forward use frameskipping, etc?

**Comment by negativeExponent** [comment]
ok, found the frameskip option. disabling it, still faster

![pce_mednafen_no_frameskip](https://user-images.githubusercontent.com/54053706/71545055-79604280-29c1-11ea-9c78-8455a1cb14d0.png)

**Comment by mrjschulte** [comment]
Is this not part of the inherent price being "paid" for having the more accurate emulation path?

**Comment by negativeExponent** [comment]
this is a mednafen_pce and libretro_pce comparison, not a pce / pce_fast comparison...

**Comment by negativeExponent** [comment]
moved to appropriate core: https://github.com/libretro/beetle-pce-libretro/issues/11
