### ISSUE TITLE
Turbografix 16 cd cue sheet issue

### ISSUE THREAD

**Issue by ghost** [libretro/beetle-pce-fast-libretro#147]
https://github.com/libretro/RetroArch/issues/10037

It was posted there but  apparently it's due to a malformed cue sheet. I had issues with bin/cue roms of Turbografx 16 cd not launching.

**Comment by hizzlekizzle** [comment]
Can you post the contents of your cue sheet?

**Comment by Gitlab1111** [comment]
FILE "Exile 2 - Wicked Phenomenon (USA)".bin" BINARY
  TRACK 01 AUDIO
    INDEX 01 00:00:00
  TRACK 02 MODE1/2352
    PREGAP 00:03:00
    INDEX 01 00:30:18
  TRACK 03 AUDIO
    PREGAP 00:02:00
    INDEX 01 02:48:62
  TRACK 04 AUDIO
    INDEX 01 03:13:39
  TRACK 05 AUDIO
    INDEX 01 05:19:16
  TRACK 06 AUDIO
    INDEX 01 07:23:20
  TRACK 07 AUDIO
    INDEX 01 09:23:61
  TRACK 08 AUDIO
    INDEX 01 11:24:15
  TRACK 09 AUDIO
    INDEX 01 13:25:02
  TRACK 10 AUDIO
    INDEX 01 15:30:38
  TRACK 11 AUDIO
    INDEX 01 17:51:16
  TRACK 12 AUDIO
    INDEX 01 20:15:43
  TRACK 13 AUDIO
    INDEX 01 21:46:16
  TRACK 14 AUDIO
    INDEX 01 24:07:05
  TRACK 15 AUDIO
    INDEX 01 26:28:06
  TRACK 16 AUDIO
    INDEX 01 28:51:66
  TRACK 17 AUDIO
    INDEX 01 31:12:40
  TRACK 18 AUDIO
    INDEX 01 32:52:05
  TRACK 19 AUDIO
    INDEX 01 34:32:25
  TRACK 20 AUDIO
    INDEX 01 36:01:39
  TRACK 21 AUDIO
    INDEX 01 38:00:29
  TRACK 22 AUDIO
    INDEX 01 38:54:05
  TRACK 23 AUDIO
    INDEX 01 39:47:40
  TRACK 24 AUDIO
    INDEX 01 40:32:19
  TRACK 25 AUDIO
    INDEX 01 41:20:70
  TRACK 26 AUDIO
    INDEX 01 42:19:56
  TRACK 27 AUDIO
    INDEX 01 43:19:60
  TRACK 28 AUDIO
    INDEX 01 44:48:04

Is that what you needed to see?

**Comment by negativeExponent** [comment]
did you at least load your cd games using the cuesheet instead of bin? coz this was the log you showed last time.

**Comment by negativeExponent** [comment]
i think this can be closed since OP has left the game...
