### ISSUE TITLE
[Ubuntu 18.04] The emulator can't change to 6-button mode when pressing L2 once

### ISSUE THREAD

**Issue by emersonnovais** [libretro/beetle-pce-fast-libretro#148]
Since the last updates, the emulator can't change to 6-button mode when pressing L2 once. To maintain the 6-button mode, the L2 may pressed all the time and annoying the gameplay. I noted this bug when try the "Tengai Makyou - Kabuki Ittou Ryoudan" (PCE-CD) and "Street Fighter II CE" (PCE). The emulator shows the message "6-button pad mode for pad1" but not maintain it. The Beetle Supergrafx core had the same problem.
[edit]: The Medafen Beetle PCE standalone core works perfect in this aspect.

My system: Ubuntu 18.04 (64 bits)
Gamepad: DS4 v2

**Comment by negativeExponent** [comment]
hi. I just tested the core (pce_fast) both with Tengai and SF2CE and both games are able to retain and configure 6-button mode pads(xbox360 controller wired-yeah i hate wireless and batteries).
Supergrafx core is broken though but its an easy fix (since i did the update)
Thanks for the report.
