### ISSUE TITLE
[RPI2] Compatibility issue?

### ISSUE THREAD

**Issue by nemo93** [libretro/beetle-pce-fast-libretro#15]
Hi there,

Just to give you an heads-up. I've been used to rely on this core to emulate the fantastic PC Engine machine and games. As I was always playing more or less the same games (with no issues whatsoever) I was surprised when I couldn't get 1941 to work. I got a black screen at launch every time whatever version of this game I'm trying to launch. The funny thing is that it works flawlessly with the beetle-supergrafx-libretro core! As RPI2 is way more punchy than RPI1 I stick to this core as it seems compat' is better/higher. 

If you want me to test with other games please let me know.
Cheers,

TS

**Comment by LodanZark** [comment]
1941 - Counter Attack, Aldynes - The Misson Code for Rage Crisis, Battle Ace, Daimakai Mura, Madou King Granzort aren't standard PC Engine games, but SuperGrafx (SGX) games.
The latest Retropie has 2 emulators for pce engine, the lr-mednafen-pce-fast and lr-mednafen-pce, the  lr-mednafen-pce can manage the SGX games, but lr-mednafen-pce-fast not, yet i'm not sure if it is a bug.

**Comment by LodanZark** [comment]
beetle-supergrafx-libretro works well because 1941 its a supergrafx game and not a standard pce game, yet there are only 4 games for it: http://gaming.wikia.com/wiki/List_of_SuperGrafx_games

**Comment by nemo93** [comment]
Silly me!! You're absolutely right!!
