### ISSUE TITLE
.zip support for CD-ROM systems?

### ISSUE THREAD

**Issue by thekiefs** [libretro/beetle-pce-fast-libretro#154]
Is there any way to bring .zip or other compression support to run games with multiple .bins and .cue that are embedded within a .zip? Right now I have to extract the .zip in order to play the game, it would be nice to skip that step if possible. There are other CD systems that crash on .zip load https://github.com/libretro/RetroArch/issues/10630 so I'm thinking it's hard to integrate this support

**Comment by negativeExponent** [comment]
crash can possibly be fixed, but no one with the right mind should be using zip, rar,7zip to load CD or HDD based games. this is the reason CHD was created so these images can stay compressed and decompress in memory in real-time.

**Comment by hizzlekizzle** [comment]
I agree with @negativeExponent and this sort of thing is generally considered a frontend's responsibility, rather than the core's.

**Comment by thekiefs** [comment]
Ok. Thnx
