### ISSUE TITLE
CD support broken (regression)

### ISSUE THREAD

**Issue by Exalm** [libretro/beetle-pce-fast-libretro#155]
![Screenshot from 2020-05-23 23-59-05](https://user-images.githubusercontent.com/1510457/82738495-7cb8e980-9d27-11ea-9562-0b084072bc69.png)

This is a regression from https://github.com/libretro/beetle-pce-fast-libretro/commit/111767c425be9d5d1f39c537d2d274a2654b50e8

x86_64, Linux (Fedora 32), Flatpak.

**Comment by twinaphex** [comment]
Hi there,

see if this fixes the issue -

https://github.com/libretro/beetle-pce-fast-libretro/commit/17ba58b4695970dad499de04a3b81777ff47c9d9

**Comment by Exalm** [comment]
Thanks, works!
