### ISSUE TITLE
Weird screen glitches for Turbo Grafx 16 games on 3ds build of Retroarch 

### ISSUE THREAD

**Issue by IceCloud76** [libretro/beetle-pce-fast-libretro#158]
I'm using a New 2DS XL and the "NEC - PC Engine / CD (Beetle PCE FAST" core for retroarch, and every game I try, including Devil's Crush and Blazing Lazers all have this screen glitch appear at the bottom of the screen.

For example in the opening scene of Blazing Lazers, there appears a line of multicolored pixels. On real 3ds hardware this is very well noticeable and happens in all games I've tried.
![Blazing_Lazers](https://user-images.githubusercontent.com/47666987/89200563-d3d40980-d575-11ea-97a5-302980eaaacc.png)

Here's my log file 
[retroarch__2020_08_03__10_48_15.log](https://github.com/libretro/beetle-pce-fast-libretro/files/5016975/retroarch__2020_08_03__10_48_15.log)

**Comment by negativeExponent** [comment]
adjust initial/last scanline. normally these areas are covered by ctr bezels

**Comment by IceCloud76** [comment]
That was it! Changing the "Last Scanline" under core options from 242 to 241 solved it.
