### ISSUE TITLE
[Wii] PC-Engine CD games do not load

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/beetle-pce-fast-libretro#16]
reporting here as discussed in: https://github.com/libretro/RetroArch/issues/2173

Libretro RetroArch 1.2.2 stable

bios syscard3.pce in retroarch system folder

black screen on trying to load game

other reports: http://libretro.com/forums/showthread.php?t=3690

**Comment by netux79** [comment]
I think this issue is solved from long time ago... please consider closing it. Thanks.
