### ISSUE TITLE
audio channels mute/balance core option

### ISSUE THREAD

**Issue by eadmaster** [libretro/beetle-pce-fast-libretro#160]
some shmup games like "Side Arms - Hyper Dyne" have an unbalanced audio channels making the BGM hard to listen while shooting.

I'd like to suggest adding some core options to mute/reduce the volume of individual audio channels like [Nestopia](https://forums.launchbox-app.com/uploads/monthly_2016_11/sound.jpg.1daaf574b34952aca281a118038b5aad.jpg) and the FCEUmm core has.

**Comment by negativeExponent** [comment]
i was under the impression you wanted volume adjustments rather than just not rendering specific channels at all. there is no such thing as a "bgm" channels as each channel represents a certain instrument or wave type (but im sure you know this). Even the shooting sfx are divided into few channels.

**Comment by negativeExponent** [comment]
nevermind.. got merged anyways.

**Comment by twinaphex** [comment]
@negativeExponent If you want me to revert the PR because something was not yet considered, then let me know.

Can you and @eadmaster come to some kind of consensus as to what should be implemented?

**Comment by negativeExponent** [comment]
nothing i can do about that anymore. the blip buffer's volume section has been removed anyways

**Comment by eadmaster** [comment]
Having individual channel volume mixing would be nice, btw i've tested this with a few affected games, and it actually helps mitigating the issue (disable the SFXs while leaving the BGM untouched):
 - in Side Arms - Hyper Dyne (U), disable channels 4 and 5
 - in Xevious - Fardraut Densetsu (J), disable channels 3 and 5

I've also checked it does not break savestates, which is important for me.

I suggest to leave this issue open as we investigate how to do individual channel volume adjustments, which may replace the "Disable Sound Channel X" core options once implemented.

**Comment by trioan** [comment]
I've done something like this for a few private builds (Mesen, Handy, NGP), although Mesen already had support for this.


For others, I looked for the ```blip_synth_offset``` locations and volume adjusted from the libretro settings. But since we have 6 channels, you may have to add an id tag to the struct to make things simpler. Because I didn't want the volume adjustment to get saved in the state, I did it during calling.

```Blip_Synth_offset(&Synth, timestamp, (samp[0] - ch->blip_prev_samp[0]) * vol_level / 100, sbuf[0]);``` in 5 gain steps because I couldn't think of a better way yet.

https://github.com/libretro/beetle-pce-fast-libretro/blob/master/mednafen/pce_fast/psg.cpp
https://github.com/libretro/beetle-pce-fast-libretro/blob/master/mednafen/pce_fast/psg.h

**Comment by eadmaster** [comment]
> For others, I looked for the `blip_synth_offset` locations and volume adjusted from the libretro settings. But since we have 6 channels, you may have to add an id tag to the struct to make things simpler. Because I didn't want the volume adjustment to get saved in the state, I did it during calling.
> 
> `Blip_Synth_offset(&Synth, timestamp, (samp[0] - ch->blip_prev_samp[0]) * vol_level / 100, sbuf[0]);` in 5 gain steps because I couldn't think of a better way yet.
> 

This has to de done for every call of `Blip_Synth_offset()`, right?

**Comment by eadmaster** [comment]
UPDATE: just tried it, and it seems to work fine!

@trioan: please confirm it is correct so i submit another PR.

**Comment by trioan** [comment]
I want to say yes! because I think it looks great (and I like how you handled it). But I defer to @negativeExponent to be safe.

**Comment by eadmaster** [comment]
new PR: https://github.com/libretro/beetle-pce-fast-libretro/pull/165

**Comment by eadmaster** [comment]
if interested also checke the pending PRs i've submitted recently to have similar options in Nestopia and a fix for Snes9x:
- https://github.com/libretro/nestopia/pull/15
- https://github.com/libretro/snes9x/pull/242
