### ISSUE TITLE
USA games not booting while JAP games does

### ISSUE THREAD

**Issue by eadmaster** [libretro/beetle-pce-fast-libretro#162]
Example hucard ROM:
`Legend of Hero Tonma (U).pce` (crc32 55E9630D) just shows a black screen, while "Legend of Hero Tonma (J)" boots and goes ingame.

I've tried resetting the system core options, but the result was the same.

**Comment by negativeExponent** [comment]
probably bad [b] hucard dump. works fine on my end.
![tonma](https://user-images.githubusercontent.com/54053706/93524505-296a4700-f967-11ea-9583-5d1659f9aa5d.png)

**Comment by negativeExponent** [comment]
update? this should be closed then

@hizzlekizzle

**Comment by eadmaster** [comment]
UPDATE: i've just verified the NoIntro USA ROM dump does boot indeed.
