### ISSUE TITLE
Duckstation core shm_open error 13

### ISSUE THREAD

**Issue by suetlung** [libretro/beetle-pce-fast-libretro#198]
Platform: ubuntu 20.14 snap store
Version: 1.9.12
Core: psx duck station
Game: super robot war alpha
File format: pbp
Issue: terminates when loading pbp rom
Error: shm_open failed (13). Seems related to the permission flag when calling it.

**Comment by twinaphex** [comment]
This has nothing to do with the beetle pce fast core though.

**Comment by suetlung** [comment]
you are right. Sorry.
