### ISSUE TITLE
RetroArch runs in background after use of the PCSX2 - PlayStation 2 Core

### ISSUE THREAD

**Issue by K0R1NN** [libretro/beetle-pce-fast-libretro#204]
I use **GOG Galaxy 2.0** launcher for my games and after launching RetroArch and playing a game using the **PCSX2 - PlayStation 2** Core, and then closing the content and RertoArch, it still seems to run in the background. I found the only way to stop it is to **End Task** it using Task Manager. (I am on Windows 10 by the way). The reason this is a problem for me is that it uses 500 - 600 MB of RAM sometimes which for my laptop of only 4 GB RAM is a huge chunk of its Memory. Another reason for this to be a problem is that GOG Galaxy 2.0 keeps track of how long you play a game and shows you your statistics. If RertoArch continues to run in the background, then GOG Galaxy 2.0 will treat it as being open and will continue to track the time, which resulted in me having four extra hours of play time than I actually should have. I hope this issue can be resolved in some update. Thank You for all your hard work and efforts to bring us this amazing software 😃 .

**Comment by LibretroAdmin** [comment]
Invalid issue report, this is the PCE Fast core.
