### ISSUE TITLE
cores need updates.

### ISSUE THREAD

**Issue by Eggo-dotcom** [libretro/beetle-pce-fast-libretro#207]
Official Mednafen is at 1.28 and has had multiple PCE/TG16 updates . Can someone update this fast core and the accurate core? (The accurate core more importantly)

**Comment by Eggo-dotcom** [comment]
1.29 stable is out, compatibility fixes to commercial titles included.

from 9.40 to now many fixes to pce......

**Comment by negativeExponent** [comment]
upstream updates does not necessarily mean its beneficial or relevant for libretro targets.

if you are having some issue with a particular game, then make a post are report about it, else requesting updates because some "upstream" has upped its version is just pointless

**Comment by Eggo-dotcom** [comment]
> upstream updates does not necessarily mean its beneficial or relevant for libretro targets.
> 
> if you are having some issue with a particular game, then make a post are report about it, else requesting updates because some "upstream" has upped its version is just pointless

So when upstream reports many compatibility fixes to pce emulation over a span of 24 months they wont effect this? 

I doubt that but ok.

**Comment by Eggo-dotcom** [comment]
> upstream updates does not necessarily mean its beneficial or relevant for libretro targets.
> 
> if you are having some issue with a particular game, then make a post are report about it, else requesting updates because some "upstream" has upped its version is just pointless

so the libretro core would of taken care of all these missing updates? (Yes all PCE Updates in how the emulator behaves)

Now dont get me wrong, if this core doesnt want to update ok fine whatever. Im just pointing out that it is missing a ton of fixes. One could do what I do, run Mednafen.

January 12, 2022:
	PCE, PCE-Fast: Initialize VCE color table memory at power-on to roughly(without probabilistic bit randomness) match test results from a
	PC Engine Duo instead of just zeroing it; fixes unreadable letters in the password entry screen of "Order of the Griffon".

January 11, 2022:
	PCE: Added patch in the "notes" subdir for extending the upper range of the "pce.slend" setting to 241(not applied in Mednafen due to increasing
	the probability of an extra 8ms of input lag with some games).

December 24, 2021:
	PCE: Fixed incomplete initialization of the VDC BG tile cache; fixes glitches after the boss explodes in "R-Type" under certain
	conditions(more likely to occur in forks of Mednafen).

ecember 31, 2020:
	
	PCE-Fast: Renamed encapsulating namespace from "PCE_Fast" to "MDFN_IEN_PCE_FAST", to match the convention of all other emulation modules.

	Made Emulated* MDFNGI objects constant, copied over to a dynamically-allocated MDFNGI assigned to MDFNGameInfo on game load.

ecember 30, 2020:

	PCE-Fast: Fixed massive overallocation of memory for the VDC background tile cache.


August 24, 2019:
	PCE: Changed the Super CD-ROM^2 memory identification signature to match a Duo instead of a PCE with a system card, to fix compatibility
	issues with some US Super CD-ROM^2 games when using a US system card image, per tip from elmer.

March 18, 2019:
	PCE: Fixed an old bug(looks like from around a decade ago) in the HES playback code; it caused periodic high IRQ latency,
	which resulted in timer IRQ-driven DDA playback sounding rougher than it should have.

November 30, 2018:
	PCE: Increased CD read startup delay per tip from dshadoff.  Fixes ADPCM voice playback	issues in "Downtown Nekketsu Monogatari" when text
	speed is set to fast.

January 12, 2018:
	
	PCE_FAST: Fixed fubared mouse emulation.

April 18, 2017:
	VB, PCE, WonderSwan, MD, GBA: Use fastcall calling convention(on 32-bit x86) in a few (more) places where it makes sense.

**Comment by Eggo-dotcom** [comment]
> January 12, 2022:
> PCE, PCE-Fast: Initialize VCE color table memory at power-on to roughly(without probabilistic bit randomness) match test results from a
> PC Engine Duo instead of just zeroing it; fixes unreadable letters in the password entry screen of "Order of the Griffon".

welll the following i can confirm is a problem (i am not surprised)

January 12, 2022:
PCE, PCE-Fast: Initialize VCE color table memory at power-on to roughly(without probabilistic bit randomness) match test results from a
PC Engine Duo instead of just zeroing it; fixes unreadable letters in the password entry screen of "Order of the Griffon".
