### ISSUE TITLE
[Suggestion] Controls Mapping

### ISSUE THREAD

**Issue by LodanZark** [libretro/beetle-pce-fast-libretro#22]
The Majority of libretro cores of platforms that has 2 buttons use the keys "BA", meanwhile this libretro core uses "BY".

Is it possible to keep "button II" as "B" and change the "button I" to "A" to keep some consistency inside Retroarch environment?

Would be nice as well the implementation of the turbo speed switch for example:
Turbo Switch for "Button II" = "button Y"
Turbo Switch for "Button I" = "button X"
Each time the button it's pressed increases one turbo level until reset to level1, with 3 levels of turbo.
level1 (no turbo) -> level2 (average speed turbo) -> level3 (fast speed turbo) -> reset to level1 -> etc.

Any plans for implementation of gamepads with 3 and 6 buttons for games alike: Barunba (3buttons), Street Fighter II' - Champion Edition (6buttons), Strip Fighter II (6buttons) ?

**Comment by fr500** [comment]
6 button works fine, there is some shortcut to enable it I don't remember.
About the map, you can just use core remapping to get what you want. I'm
pretty sure some people are happy with the BY map by default

**Comment by LodanZark** [comment]
I'm not sure if the majority of people is happy ith BY map, I've saw some threats related with this subject, for example:
http://libretro.com/forums/showthread.php?t=66
https://www.raspberrypi.org/forums/viewtopic.php?f=78&t=13600&start=300

Mainly the problem with this mapping scheme its the gamepads with 2 buttons (most likely NES gamepad clones), which has only the button A and B (which are the standard buttons for platforms that requires 2 buttons).

Anyway ithink there is a solution that could fix this situation for different mappings in a single core, for example the "lr-fba-next" core has a 3 mapping presets (gamepad, arcade, newgen) over the value "fba-controls" inside the "retroarch-core-options.cfg" file, think think a similar procedure could be used in this situation.

**Comment by fr500** [comment]
no, we have core input remapping, fba is an exception, because arcades don't lend itself to retropad mapping. We won't make it a rule
