### ISSUE TITLE
Pop'n Magic (Japan) boot error on FAST core only

### ISSUE THREAD

**Issue by InquisitiveCoder** [libretro/beetle-pce-fast-libretro#232]
When I try to run _Pop'n Magic (Japan)_ using the FAST core, it gives a bootup error (based on Google Lens it seems to be saying the System Card isn't inserted.) Starts up just fine on the cycle-accurate core. The SHA1s match Redump.

![Pop'n Magic (Japan)-241018-213549](https://github.com/user-attachments/assets/1fdf1692-cac6-4231-a595-4cd4aed64143)

RetroArch version: 1.91.1
OS: Windows 11 Home
CPU Architecture: x64
Beetle PCE FAST: v1.31.0.0. 97b1fae
Beetle PCE: v1.29.0 6f28995

**Comment by negativeExponent** [comment]
its literally telling you the issue is, you are not using the correct system card. in most cases you should be using systemcar3 for all PCECD titles.

**Comment by InquisitiveCoder** [comment]
My bad, I did use System Card 3 but I just double checked the md5 hash of syscard3.pce and it didn't match. The fact that it booted up on the cycle-accurate core made me think it was an issue in the fast core. Closing this.
