### ISSUE TITLE
Recent commit broke MODE1/2048 data tracks compatibility

### ISSUE THREAD

**Issue by vanfanel** [libretro/beetle-pce-fast-libretro#32]
Hi,

I have this Akumajou Dracula english patched that has MODE1/2048 format for data tracks. I have been using it with the mednafen core for years now.
Since this exact commit: https://github.com/libretro/beetle-pce-fast-libretro/commit/7aaa4ed614836fdad67e7ba3e4208f8de4f10d45
...it hangs in the "just a momment" syscard message, and sends
`CC Error: 03 11 05`
constantly to the console.

Maybe MODE1/2048 compatibility was disabled on mainline mednafen and the core inherited that with that cd-rom code backporting?
Games using MODE1/2352 for data tracks work well.

Any translations of this game available online are MODE1/2048, and in fact applying the translation patch legally available here: http://www.romhacking.net/translations/846/
will result in MODE1/2048 data tracks.

**Comment by twinaphex** [comment]
Upload it somewhere so I can test it.

**Comment by vanfanel** [comment]
@twinaphex : https://www.dropbox.com/s/pbimw8nahc01sn5/Castlevania_Rondo_of_Blood-ENGLISH.zip?dl=0

**Comment by twinaphex** [comment]
Thanks.

**Comment by twinaphex** [comment]
Should be fixed now with the upgrade to the new CD-ROM code.

Tested the ISO, but test it out on your end as well to confirm it's been fixed.

**Comment by vanfanel** [comment]
@twinaphex This is now fixed, had the game running in demo mode for 1 hour with no loading problems.
