### ISSUE TITLE
Games stay unzipped

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/beetle-pce-fast-libretro#41]
Pce files stay in the rom directory.

[It happened in the past and got fixed.](https://github.com/Tatsuya79/mednafen-libretro/commit/69fbd78675fe0eee01b89bbcf8b1e2c07f2a9090) (old code before rewrite and PCE/SGX separation)

Doesn't happen with the SuperGrafx core.

**Comment by Tatsuya79** [comment]
It's windows specific (win 7 x64 here)?
Can't find any pce files left out on android scanning everything with root access.

**Comment by Awakened0** [comment]
I'll just mention this is still a problem on Win10 x64. Just like the Neo Geo Pocket core.

**Comment by Tatsuya79** [comment]
Fixed by https://github.com/libretro/beetle-pce-fast-libretro/pull/70
