### ISSUE TITLE
PCECD iso with mp3

### ISSUE THREAD

**Issue by azvarel** [libretro/beetle-pce-fast-libretro#47]
I am a recalbox user and realized that Mega CD games do not work iso with mp3, freeing up more space on the microsd card, which would be a great implementation.

**Comment by sergiobenrocha2** [comment]
Use OGG instead, it works and it's better than mp3 (if you convert directly from raw data like bin or WAV, of course).

**Comment by twinaphex** [comment]
We might at some point add it but right now it's not within the scope of the project.  For now, consider it a 'wontfix', which will eventually turn into a 'maybe'.
