### ISSUE TITLE
noise only on audio tracks with latest commit b3827d

### ISSUE THREAD

**Issue by retro-wertz** [libretro/beetle-pce-fast-libretro#54]
https://github.com/libretro/beetle-pce-fast-libretro/commit/b3827d92fdbfde9d146dfbffe0abc400ac0a09a6

this does load and now plays cue files with .wav files, but breaks .ogg and other audio format (noise only)

**Comment by sergiobenrocha2** [comment]
You probably have a malformed cue sheet. It should be something like this for .ogg:

```
FILE "Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 01).ogg" OGG
  TRACK 01 AUDIO
    INDEX 01 00:00:00
```

Or

```
FILE "Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 01).ogg" VORBIS
  TRACK 01 AUDIO
    INDEX 01 00:00:00
```

This will not work, which I think it's your case:

```
FILE "Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 01).ogg" WAVE
  TRACK 01 AUDIO
    INDEX 01 00:00:00
```

**Comment by retro-wertz** [comment]
done, fixed cue sheet-although i do not understand the necessity of this when it comes to retroarch.

**Comment by sergiobenrocha2** [comment]
Take a look at http://wiki.hydrogenaud.io/index.php?title=Cue_sheet#Most_often_used

"Valid file types are WAVE, MP3, AIFF, BINARY and MOTOROLA. Other formats, such as the lossless formats WavPack or FLAC, can also be used under the WAVE file type."

cue sheet is not a very strong standard. It make sense to use OGG for .ogg files when you have MP3 for .mp3.
