### ISSUE TITLE
Ginga Fukei Densetsu - Sapphire (NTSC-J) ISO Not Working

### ISSUE THREAD

**Issue by azvarel** [libretro/beetle-pce-fast-libretro#55]
This ISO not working I already checked the .cue, I already downloaded other isos of this game and it just does not run, another game that I tested and did not work was Super Daisenryaku

**Comment by Tatsuya79** [comment]
It works for me, don't know what your problem is.

**Comment by azvarel** [comment]
@Tatsuya79 I choose the game, enter the bios where it asks to press key to run it simply is not loaded, back to the selection of games only with Sapphire and with Super Daisenryaku, if you can help me making available these isos since it works with you...

**Comment by sergiobenrocha2** [comment]
It's working here too. Probably a bad dump. You should have this (.cue + 17 .bin):

http://redump.org/disc/37047/

**Comment by azvarel** [comment]
@sergiobenrocha2 I downloaded and the problem still persists, it does that it will open and then back to the list of games.

I use recalbox in rpi3

**Comment by sergiobenrocha2** [comment]
What version does recalbox use?

**Comment by azvarel** [comment]
4.0.2
or 4.1 unstable
I have 2 rpi3

**Comment by sergiobenrocha2** [comment]
Uh, I asked the core version

**Comment by azvarel** [comment]
@sergiobenrocha2 
Sorry,
core 0.9.38.7
