### ISSUE TITLE
(GX) Loading .cue with OGG Vorbis kicks you out of RetroArch

### ISSUE THREAD

**Issue by SuperrSonic** [libretro/beetle-pce-fast-libretro#9]
I've tested the same games on the main version(WiiMednafen in this case) and they work fine.

Same thing happens in the Genesis Plus GX core.

**Comment by netux79** [comment]
Is this an issue that would get be fixed? Why cores in retroarch don´t support ogg even if it is supported in the original emulator. Talking of Wii in this case which I think is the same as the above report. Thanks!

**Comment by netux79** [comment]
Issue has been fixed on commit c8d581c2. Please proceed to close this issue.
