### ISSUE TITLE
Crashing on Android

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/beetle-pce-fast-libretro#90]
It's crashing on Android 7.0, last commit fde5eac

**Comment by SapphireTactician** [comment]
Latest commit as of writing this reply is 11f7aaa . I cannot reproduce any crash on Android. Please update your core and try again. If issue persists, please specify which version of Android you're using and which game(s) you tried playing.

**Comment by sergiobenrocha2** [comment]
Fixed in some commit
